name: CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/ness-fastapi
  VERSION: ${{ github.sha }}
  NAME: ness-fastapi
  # Docker image 를 ghcr.io 에 올릴 때 우리의github이름/이미지이름 으로 저장한다. 이미지이름을 정해주면 된다.
  # Docker image 의 이름을 newproject 이라고 해놓은 것. 이름 뭐할지 정하면 된다.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

# EC2 볼륨 16기가로 늘려서 테스트 -> 파티션 용량 조절 필요
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-NESS ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create .env file
        run: |
          echo NAME=${{ env.NAME }} > .env
          echo VERSION=${{ env.VERSION }} >> .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          echo CHROMA_DB_IP_ADDRESS=${{ secrets.CHROMA_DB_IP_ADDRESS }} >> .env

      - name: Remove old Docker image
        run: docker rmi -f $(docker images -aq) || true #docker rmi -f ${{ env.DOCKER_IMAGE }}:latest || true

      - name: Docker run
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          docker stop ${{ env.NAME }} || true
          docker rm ${{ env.NAME }} || true
          docker run -d -p 3000:3000 --name ${{ env.NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest